[[redirects]]
  from = "/junior"
  to = "https://tally.so/r/w79g82"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/junior"
  to = "https://tally.so/r/w79g82"
  status = 301

